# Generated by Django 6.0.4 on 2026-04-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('routes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airportroute',
            name='position',
            field=models.CharField(max_length=100),
        ),
    ]
